import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AppContext } from "src/context/app";
import { ErrorContextProvider } from "src/context/error";
import { revalidatePath } from "next/cache";

const popins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Finanzas App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/icons/icon-light.svg",
        href: "/icons/icon-light.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/icons/icon-dark.svg",
        href: "/icons/icon-dark.svg",
      },
    ],
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  revalidatePath("/data", "layout")
  return (
    <html lang="es">
      <body className={popins.className}>
        <ErrorContextProvider>
          <AppContext>
            {children}
          </AppContext>
        </ErrorContextProvider>
      </body>
    </html>
  );
}
