import type { Metadata } from "next";
import { ErrorContextProvider } from "src/context/error";
import { SideMenu } from "../../components/data/SideMenu";
import "../globals.css"
import "@assets/css/data.css"
import Error from "@components/app/Error";
import { DataConfig } from "@context/data";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Finanzas App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/icons/icon-light.svg",
        href: "/icons/icon-light.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/icons/icon-dark.svg",
        href: "/icons/icon-dark.svg",
      },
    ],
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="data-layout">
        <Suspense>
          <DataConfig>
            <SideMenu />
            <div className="md:h-screen md:overflow-y-scroll">
              <ErrorContextProvider>{children}</ErrorContextProvider>
            </div>
          </DataConfig>
        </Suspense>
      </div>
      <Error />
    </>
  );
}
